language: java
sudo: false

cache:
  directories:
    - "$HOME/.m2"

before_cache:
  - rm -rf $HOME/.m2/repository/com/sharedexpenses

before_script:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)

jdk:
  - oraclejdk11